---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgC3MV5Ks4yKPR+mu3DL/nadbtQdl+cO6PTKScw4WdHocp/yyisoYU1rdWuUWJtuKdXENeK9TV5MWqGK7MI5lbWgfhIGnsd6xLuWbuWdqEmdnXCcRI3VyoNteO7L94jL1EJJljeqb1OhKqM2NGCXVZ6o0Tm3FfXu9CP/J/1KQdXAvsLHKY3EW7jx9aRu9GA1G5dIwKNO2y4uJXfdYpOImKkvD+ksxQaNEpOmkQSooKMm1CpPZ6TZltA5xivWwbWP3OGjRwbW01bX7TZ1mYt4hi1uNHj7xOr8pWFO1P3XO46KDGZ5Wx3eZrFgElyPXEuhx4d5ELuUtzt9ZC+KP3s1T4CXl34dzhmMCk5P61XSatVbd8RCCvxnDeYFobwRev1SOYnN/Gs4XWpoXoXG9hoU6twBKltys1kC+RWRVsOFyUKL3FoN6n7s6MTilrVuJYMmXbLOjolbuBTOiIpn1Vdz1vKVraXh2hBY5xdy9zVbHVtvhWV3FXyKn+S7bSCB1VcyO8SSa4EK6BCgP3yFJzD0SdVkGn7NLQd7qm8BkPGGh6h/oaX3TRhHZ5OIWLeQ0I/8/812DK7NMsp+nDMZQPfWJi4sJ0WKUIWU3EfX7BGwgP5ftftRBiEle27jTJ1auH80pZSnVSnOi21IUFc3iCCkXFPr2F7A2VNS0ioZTZUtt3vC07MgheSDtYhW1MnuFz5i0SaRyWRu71mtq/zM4NsRCJ3TdfMK
    STRIPE_API_KEY: AgB37gzqJg4KsExHN5iiOQupw2xbYEEKdd/NUzU137UGT7rvkA9TELcj1YnZUfgKxYJm+1FupbvBBw8SSoyAXkVIf4e50ca5wS5Lsbn+1D5G+Ljy0w/YLwlmcLhsF7BruaamTSjpneKWTsCvrx3C419dSVVEHcCE3ingpAJ+OoZP0VYIqMnGl7J8KcN+EPDi7Ztbfc226EXf7KV+0kVoocT3EGG3oPbwjxG7G7XO3cfcajrR4xHpsetfPHZeCqFwjlfHcFSd9/vqMeCNsJ5f5nkXO7W/lDbuQfXlfGTl1MthcYAHN53cLH6HfcfrxTB+zBGvTsFNeZurxkPnhIjvAxVGAX+nAW/WkMreNBK1KRHGBv3Lrn9XgAp12ngxQfWXlVG9lTySZbpsuiHDeCE95FpbdFJg+UPJgNmkL4Egpwa3i3zlH2uc56evmUsXgmkQ8Tdvfcex5DWUl5rOCRy/cpIrw1F4k6Oe4RBu/sSisutdMWKMYfyn7sqV63KC7nhPI1Ca9z43wHAdCyGTz4qipPFjzCIRllP8QHb3oiS4VPSDld/29Q6W+tNUgm+l61n2tkH1LIwHhZskHLJJ3syNNkfSdRpMezCaWH6SpshivpDBFGVf5ofAYYX6jG0B3THajKvkfqYQQ+sXS9gQm7LyATXXDD6COL6SmmaSv8bYgAnuuCj/GevVbFwxV46nAa1vgMARv8GTAbMNkbjbpdN2p4Ub
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
