name: Secure CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      
        with:
          scan-type: fs
          scan-ref: .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:- name: Run Trivy Filesystem Scan
  uses: aquasecurity/trivy-action@master
  with:
    scan-type: fs
    scan-ref: .
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/ledger-api:latest -f app/Dockerfile.secure app

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/ledger-api:latest